6:
	gcc myecho.c -o echo

7:
	gcc snooze.c -o snooze

20:
	gcc myls.c -o myls

22:
	gcc mysystem.c -o mysystem

24:
	gcc 8_24.c -o 8_24

25:
	gcc tfgets.c -o tfgets

.PHONY: clean
clean:
	-rm myecho snooze myls mysystem 8_24 tfgets